"""PersonaNexus ClawHub Skill -- Build AI agent personalities with business frameworks."""

__version__ = "1.5.0"

from personanexus_skill.compiler import (
    OpenClawCompiler,
    SystemPromptCompiler,
    compile_identity,
)
from personanexus_skill.dynamics import (
    DynamicSession,
    DynamicsResult,
    InteractionContext,
    apply_dynamics_to_traits,
    clamp,
    compile_with_adjusted_traits,
    context_from_state,
    evaluate_memory_influences,
    evaluate_trigger,
    evaluate_triggers,
    get_mode_by_name,
    get_mood_by_name,
    resolve_mode,
    resolve_mood,
    run_dynamics_pipeline,
)
from personanexus_skill.memory import (
    MemoryBackendJSON,
    UserState,
    increment_custom,
    record_interaction,
    update_sentiment,
    update_trust,
)
from personanexus_skill.parser import (
    IdentityParser,
    parse_file,
    parse_identity_file,
    parse_yaml,
)
from personanexus_skill.personality import (
    compute_personality_traits,
    disc_to_traits,
    get_disc_preset,
    get_jungian_preset,
    jungian_to_traits,
    list_disc_presets,
    list_jungian_presets,
    ocean_to_traits,
    traits_to_disc,
    traits_to_jungian,
    traits_to_ocean,
)
from personanexus_skill.types import (
    TRAIT_ORDER,
    AgentIdentity,
    DiscProfile,
    DynamicMode,
    DynamicMood,
    DynamicsConfig,
    DynamicTrigger,
    JungianProfile,
    MemoryInfluenceRule,
    OceanProfile,
    PersonalityMode,
    PersonalityProfile,
)
from personanexus_skill.validator import IdentityValidator, ValidationResult

__all__ = [
    "AgentIdentity",
    "DiscProfile",
    "DynamicMood",
    "DynamicMode",
    "DynamicSession",
    "DynamicsConfig",
    "DynamicsResult",
    "DynamicTrigger",
    "IdentityParser",
    "IdentityValidator",
    "InteractionContext",
    "JungianProfile",
    "MemoryBackendJSON",
    "MemoryInfluenceRule",
    "OceanProfile",
    "OpenClawCompiler",
    "PersonalityMode",
    "PersonalityProfile",
    "SystemPromptCompiler",
    "TRAIT_ORDER",
    "UserState",
    "ValidationResult",
    "apply_dynamics_to_traits",
    "clamp",
    "compile_identity",
    "compile_with_adjusted_traits",
    "compute_personality_traits",
    "context_from_state",
    "disc_to_traits",
    "evaluate_memory_influences",
    "evaluate_trigger",
    "evaluate_triggers",
    "get_disc_preset",
    "get_jungian_preset",
    "get_mood_by_name",
    "get_mode_by_name",
    "increment_custom",
    "jungian_to_traits",
    "list_disc_presets",
    "list_jungian_presets",
    "ocean_to_traits",
    "parse_file",
    "parse_identity_file",
    "parse_yaml",
    "record_interaction",
    "resolve_mood",
    "resolve_mode",
    "run_dynamics_pipeline",
    "traits_to_disc",
    "traits_to_jungian",
    "traits_to_ocean",
    "update_sentiment",
    "update_trust",
]
